### ISSUE TITLE
Add main to bower entry

### ISSUE THREAD

**Issue by treygriffith** [treygriffith/FileSaver.js#1]
@mjrk, I'm tracking this here. Feel free to open a PR for this.

https://github.com/eligrey/FileSaver.js/pull/136#issuecomment-142643809 says:

> Could you add a main entry too?
> 
> ```
> "main": [
>   "Filesaver.js"
> ],
> ```

**Comment by mjrk** [comment]
Yes, I noticed - the main entry is there!

If you put in your bower.json

```
"dependencies": {
  "file-saver": "*"
}
```

`bower install` will install

```
 bower FileSaver#*           not-cached git://github.com/eligrey/FileSaver.js.git#*
```

and you get the warning and cannot inject automatically with grunt

```
bower invalid-meta  file-saver is missing "main" entry in bower.json
```

because of the automatically generated `.bower.json` file that does not contain a main entry.

So, one will use

```
"dependencies": {
  "file-saver": "Teleborder/FileSaver.js"
}
```

You live and learn.

Thanks for you bower.json repo, btw!
